name: Build postgres docker image
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ secrets.DB_HOST }}
          private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Fetch latest dump
        run: scp circle@${{ secrets.DB_HOST }}/anon_production_dump.sql.gz ./db.sql.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image identifiers
        id: image
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Get date-based docker tag
        uses: josStorer/get-current-time@v2.0.1
        id: tag
        with:
          format: YYYYMMDD
          utcOffset: "+03:00"

      - name: Build the image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ steps.image.outputs.lowercase }}:latest
            ghcr.io/${{ steps.image.outputs.lowercase }}:{{ steps.tag.outputs.formattedTime }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
